name: BCNotification
on: 
  issues:
    types: [edited, labeled]
    
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      if: github.actor == 'MondayLesley'

    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1.0.0
  
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SCRIPT_FILEPATH: .github/sendgrid.js
